; OpenSnowstorm Options
; Game Speed: 1=1X, 2=2X, 4=4X, 8=8X
game_speed=4
sfx_volume=50
music_volume=50
volume=50
sound=1
unit_speech=1
unit_sounds=1
fog_of_war=1
mouse_scroll=3
keyboard_scroll=3
fullscreen=0
show_objectives=1
show_health_bars=1

; Hotkeys (ASCII characters)
hotkey_stop=s
hotkey_hold=h
hotkey_attack=a
hotkey_patrol=t
hotkey_build=b
hotkey_cloak=c
hotkey_burrow=b
hotkey_siege=g
hotkey_stim=i
hotkey_unload=l
hotkey_lift=l
hotkey_return_cargo=r
hotkey_merge=m
hotkey_cancel=x
